#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [ ]:
!pip install numpy

In [1]:
import numpy as np

## create array using numpy
##create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## 1 d array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  ##1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)
print(arr2[0][1])

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)
2


In [3]:
arr = np.array([

    [                   # ── Level 0 ── (outermost list)
        [               # ── Level 1 ── (next inner list)
            [1, 2],    # ── Level 2 index 0 ── a list of length 2
            [3, 4]     # ── Level 2 index 1 ── another list of length 2
        ]
    ]
])

# Access the element at layer 2, row 1, column 1:
print(arr[0][0][1][0])  # → 4
print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)

3
Array:
 [[[[1 2]
   [3 4]]]]
Shape: (1, 1, 2, 2)
Number of dimensions: 4
Size (number of elements): 4
Data type: int64
Item size (in bytes): 8


arr = np.array([

    [                   # ── Level 0 ── (outermost list)
        [               # ── Level 1 ── (next inner list)
            [1, 2],    # ── Level 2 index 0 ── a list of length 2
            [3, 4]     # ── Level 2 index 1 ── another list of length 2
        ]
    ]
])

Dimension 0

Look at the outermost list:

[

  [ ... ]    # Only one element here

]

Length = 1 → so shape[0] = 1.

Dimension 1

Inside that single element is another list:

[

  [ [1,2], [3,4] ]   # Only one element here as well

]

Length = 1 → so shape[1] = 1.

Dimension 2

That element contains two lists (the “rows”):


[

  [1, 2],   # row 0
  
  [3, 4]    # row 1

]

Length = 2 → so shape[2] = 2.

Dimension 3

Each of those rows is itself a list of two numbers:

[1, 2]   # length 2

[3, 4]   # length 2

Length = 2 → so shape[3] = 2.

Putting it all together:


shape = (len(L0), len(L1), len(L2), len(L3))
      = (1,         1,         2,         2)
      
where

L0 is the outermost list,

L1 is its single child list,

L2 is that child’s list of two rows,

L3 is each row’s list of two elements.

Hence the array’s shape is 4‑D with dimensions 1×1×2×2.

In [ ]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Number of dimensions: 2
Size (number of elements): 9
Data type: int64
Item size (in bytes): 8


In [ ]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [ ]:
## Universal Function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)



Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(arr[1:,1:3])

[[[ 7  8]]

 [[11 12]]

 [[11 12]]]


In [ ]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [ ]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [ ]:
## Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)



Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


np.mean(data) sums up all the elements in data and divides by the number of elements.

np.median(data) sorts your data and picks the middle value (or the average of the two middle values if there’s an even number of points).

In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [ ]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

Computing the Standard Deviation



std_dev = np.std(data)
print("Standard Deviation:", std_dev)
What the code does:

np.std(data) computes the square root of the average squared deviation of each point from the mean.

Formula:

𝜎
=
1
𝑁
∑
𝑖
=
1
𝑁
(
𝑥
𝑖
−
𝜇
)
2
σ=
N
1
​
  
i=1
∑
N
​
 (x
i
​
 −μ)
2

​

where
𝜇
μ is the mean.

In our example:

Deviations:
[
−
3
,
−
1
,
−
1
,
−
1
,
0
,
0
,
2
,
4
]
[−3,−1,−1,−1,0,0,2,4]

Squared:
[
9
,
1
,
1
,
1
,
0
,
0
,
4
,
16
]
[9,1,1,1,0,0,4,16]

Mean of squares:
(
9
+
1
+
1
+
1
+
0
+
0
+
4
+
16
)
/
8
=
32
/
8
=
4
(9+1+1+1+0+0+4+16)/8=32/8=4

Std dev =
4
=
2.0
4
​
 =2.0.

Interpretation:
Standard deviation measures how “spread out” the values are around the mean. A low σ means data are tightly clustered; a high σ means more dispersed.